### PR TITLE
Update dev-setup.md

### LINKED ISSUE #745: Documentation about dev setup is a bit confusing.
https://github.com/deptofdefense/anet/blob/master/docs/dev-setup.md#set-up-gradle-eclipse-and-npm shows the initial setup, but its a bit confusing in that some of the steps shown at the same level are really associated with the previous step (mixes "what is needed" with "how to do it").

The markdown actually has indentation that shows this, but its a bit off, and the rendered version ends up with 14 steps at the same level.

### PR DESCRIPTION
**Pull request by bradh**
Fix indenting that was a bit confusing in terms of what was happening vs how to do it.

Resolves #745

### CODE REVIEW

**Comment by tomberek** [comment]
@bradh : Thanks for the commit. We'll re-merge, but need just a slight addition. Please sign DCO according to [this document](/deptofdefense/anet/blob/master/CONTRIBUTING.md). Just add your name to the appropriate section [here](/deptofdefense/anet/blob/master/Contributors.md)

**Comment by bradh** [comment]
Unfortunate that this was necessary for such a trivial change, but PR submitted.

**Comment by bradh** [comment]
Is anything more needed to get this re-merged?

**Comment by tomberek** [comment]
@bradh That was my mistake with regards to the DCO. Thanks for the reminder to re-merge.

**Pull request merged**
